Ttree:
  JsonStore:
    Manager:
      documentTypes: []

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Ttree.JsonStore.Manager: ['Modules']

    modules:
      management:
        submodules:
          jsonStore:
            label: 'Ttree.JsonStore.Manager:Modules:jsonStore.label'
            controller: '\Ttree\JsonStore\Manager\Controller\Module\Management\JsonStoreController'
            description: 'Ttree.JsonStore.Manager:Modules:jsonStore.description'
            icon: 'fas fa-book'
            privilegeTarget: 'Ttree.JsonStore.Manager:BackendModule'
